ALTER TABLE session_album_photos
  ADD COLUMN object_key VARCHAR(512) NULL AFTER photo_url,
  ADD COLUMN object_etag VARCHAR(128) NULL AFTER object_key,
  ADD UNIQUE KEY uniq_session_album_photos_object_key (object_key);

CREATE TABLE session_album_upload_intents (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  session_id BIGINT UNSIGNED NULL,
  kind VARCHAR(32) NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  source_content_type VARCHAR(64) NOT NULL,
  source_byte_size BIGINT UNSIGNED NULL,
  max_source_byte_size BIGINT UNSIGNED NOT NULL,
  stored_content_type VARCHAR(64) NULL,
  stored_byte_size BIGINT UNSIGNED NULL,
  stored_width INT UNSIGNED NULL,
  stored_height INT UNSIGNED NULL,
  object_etag VARCHAR(128) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  upload_expires_at DATETIME NOT NULL,
  last_authorization_expires_at DATETIME NULL,
  finalize_deadline_at DATETIME NOT NULL,
  cleanup_not_before DATETIME NOT NULL,
  cleanup_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  last_error_code VARCHAR(64) NULL,
  lease_token CHAR(36) NULL,
  lease_expires_at DATETIME NULL,
  media_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  finalized_at DATETIME NULL,
  UNIQUE KEY uniq_album_upload_intents_object_key (object_key),
  UNIQUE KEY uniq_album_upload_intents_media_id (media_id),
  INDEX idx_album_upload_intents_cleanup (status, cleanup_not_before, next_retry_at),
  INDEX idx_album_upload_intents_user_created (user_id, created_at),
  INDEX idx_album_upload_intents_lease (status, lease_expires_at),
  CONSTRAINT fk_album_upload_intents_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_album_upload_intents_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_album_upload_intents_media FOREIGN KEY (media_id) REFERENCES session_album_photos(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE session_album_object_cleanup_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  media_id BIGINT UNSIGNED NULL,
  session_id BIGINT UNSIGNED NULL,
  storage_kind VARCHAR(16) NOT NULL,
  object_key VARCHAR(512) NULL,
  local_path VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  last_error_code VARCHAR(64) NULL,
  lease_token CHAR(36) NULL,
  lease_expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  UNIQUE KEY uniq_album_object_cleanup_media (media_id),
  INDEX idx_album_object_cleanup_claim (status, next_retry_at, lease_expires_at),
  INDEX idx_album_object_cleanup_session (session_id, created_at),
  CONSTRAINT fk_album_object_cleanup_media FOREIGN KEY (media_id) REFERENCES session_album_photos(id) ON DELETE SET NULL,
  CONSTRAINT fk_album_object_cleanup_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
